#!/bin/sh

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end
#
#  ident	$Id$
#
#  This script updates the fsmgr.jar file, files in js/jsp/html/images
#  directory.  This is a shortcut for developers to update their files in
#  the develepment stage.  Please forward all the comments or report bugs to
#  Ronald So (x28739) ronald.so@sun.com.
#
#  Note: This script is explicitly used by SAM-QFS Manager only (English)
#
#

BIN_DIR=/usr/sbin
SMCWEBSERVER=${BIN_DIR}/smcwebserver
#WORKSPACE=/net/crouch/export/ws1/ronaldso/samqfs_51
DOMAIN=`uname`
OS=`uname -r`
ARCH=`/usr/bin/uname -p`
PLATFORM=${DOMAIN}_${OS}_${ARCH}_DEBUG
JNI_JAR_NAME=fsmgmtjni.jar
DEPLOY=/opt/SUNWfsmgr/samqfsui

FLAG_JAR=0
FLAG_JSP=0
FLAG_JS=0
FLAG_OTHER=0

#
# Check if user is a superuser.
#
check_su()
{
    id=`/bin/id | awk -F"(" '{print $1}' | awk -F"=" '{print $2}'`

    if [ "${id}" != "0" ]; then
        echo "You need to be super-user to run this script!"
        exit 1
    fi
}

copy_jar() {

    echo "Copy everything in WEB-INF...\c"
     /usr/bin/cp ${WORKSPACE}/src/samqfsui/WEB-INF/*.xml  /opt/SUNWfsmgr/samqfsui/WEB-INF
    /usr/bin/cp ${WORKSPACE}/src/samqfsui/obj/${PLATFORM}/WEB-INF/lib/fsmgr.jar /opt/SUNWfsmgr/samqfsui/WEB-INF/lib
    echo "done!"

    echo "Copying JNI JAR file...\c"
    /usr/bin/cp ${WORKSPACE}/src/lib/sammgmtjni/obj/${PLATFORM}/${JNI_JAR_NAME} /opt/SUNWfsmgr/samqfsui/WEB-INF/lib
    echo "done!"
}

copy_jsp() {
    echo "Copying JSP files to ${DEPLOY}/jsp ...\c"
    /usr/bin/cp -r ${WORKSPACE}/src/samqfsui/jsp/* ${DEPLOY}/jsp
    echo "done!"
}

copy_js() {
    echo "Copying JS files to ${DEPLOY}/js ...\c"
    /usr/bin/cp -r ${WORKSPACE}/src/samqfsui/js/* ${DEPLOY}/js
    echo "done!"
}

copy_others() {
    echo "Copying HTML files, images...\c"
    /usr/bin/cp -r ${WORKSPACE}/src/samqfsui/html/* ${DEPLOY}/html
    /usr/bin/cp -r ${WORKSPACE}/src/samqfsui/images/* ${DEPLOY}/images
    /usr/bin/cp -r ${WORKSPACE}/src/samqfsui/app.xml ${DEPLOY}/app.xml
    echo "done!"
}

renew_app() {

    ${SMCWEBSERVER} stop

    # Unregister and re-register JNI
    wcadmin remove  -l -a samqfsui /opt/SUNWfsmgr/samqfsui/WEB-INF/lib/${JNI_JAR_NAME}
    wcadmin add -l -a samqfsui /opt/SUNWfsmgr/samqfsui/WEB-INF/lib/${JNI_JAR_NAME}
    
    wcadmin reload -x samqfsui

    cd /
    ${SMCWEBSERVER} start
}

show_syntax() {

    echo "\nSyntax: renew architecture {target(s)}"
    echo "\n\tarchitecture={i386|sparc}"
    echo "\n\ttarget={jsp|js|jar|other}\n"

    echo "e.g. renew i386          -> update all files includes all four"
    echo "                            targets on a Solaris 10 i386 platform"
    echo "e.g. renew sparc jar jsp -> update the JAR file and all JSP files"
    echo "                            on a S10 sparc platform\n\n"
}

# Check the syntax and perform the appropriate task
echo ""

check_su

if [ "x${WORKSPACE}" = "x" ]; then
    echo "Please set WORKSPACE variable to your tree location!"
    echo "e.g. /net/crouch.east/export/ws1/ronaldso/samqfs_51\n"
    exit 1
fi

if [ $# -eq 1 ]; then
    if [ $1 = "-h" ]; then
        show_syntax
	exit 1
    fi
fi

echo "PLATFORM is ${PLATFORM}\n"

if [ $ARCH != "sparc" -a $ARCH != "i386" ]; then
    echo "Invalid system architecture specified! ($1) architecture unknown"
    echo "arch={sparc|i386}"
    echo ""
    exit 1
fi

if [ $# -eq 0 ]; then
    FLAG_JAR=1
    FLAG_JSP=1
    FLAG_JS=1
    FLAG_OTHER=1
else
    LOOP=1
    for param in $*
    do
        if [ $LOOP -gt 0 ]; then
            if [ $param = "jsp" ]; then
                FLAG_JSP=1
            elif [ $param = "jar" ]; then
                FLAG_JAR=1
            elif [ $param = "js" ]; then
                FLAG_JS=1
            elif [ $param = "other" ]; then
                FLAG_OTHER=1
            else
                echo "Invalid flag ($param) specified!"
                exit 1
            fi
        fi

        LOOP=`expr $LOOP + 1`
    done
fi

if [ $FLAG_JAR -eq 1 ]; then
    copy_jar
fi

if [ $FLAG_JS -eq 1 ]; then
    copy_js
fi

if [ $FLAG_JSP -eq 1 ]; then
    copy_jsp
fi

if [ $FLAG_OTHER -eq 1 ]; then
    copy_others
fi

echo ""

renew_app

echo ""

exit 0
