.\" $Revision: 1.16 $
.ds ]W Sun Microsystems
.\" SAM-QFS_notice_begin
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at pkg/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
.\" Use is subject to license terms.
.\"
.\" SAM-QFS_notice_end
.TH sam_odlabel 3 "05 Nov 2001"
.SH NAME
sam_odlabel \- Label an optical disk on the specified device
.SH SYNOPSIS
.LP
.BI "cc [ " "flag"
.BI " ... ] " "file"
.BI " ... -L/opt/SUNWsamfs/lib -lsamapi [ " "library" " ... ]"
.LP
.nf
.ft 3
#include "/opt/SUNWsamfs/include/samapi.h"
.ft
.fi
.LP
.BI "int sam_odlabel(ushort_t " "eq_ord" ,
.BI "char *" "new_vsn" ,
.BI "char *" "old_vsn" ,
.BI "uint_t " "ea" ,
.BI "int " "modifier",
.BI "char *" "use_info" ,
.BI "int " "erase" ,
.BI "int " "wait_response" );
.SH DESCRIPTION
.PP
.B sam_odlabel(\|)
labels an optical disk on the specified device with equipment ordinal
.I eq_ord
and, if the device is a robotic media
changer, a
.I ea
must be specified.  If
.I old_vsn
is specified as a NULL pointer, the media will be assumed to be not labeled
and a new label will be written.  A
.I new_vsn
must be specified.  A VSN must be one to thirty-one characters in length.
A
.B VOL
(volume) and a
.B PAR
(partition) label are written.  These labels conform to ISO standard
IEC13346.  The data portion follow ISO standard TC97SC23.
.PP
If
.I erase
is specified as nonzero, the media is completely erased before a label is
written.
.PP
The call will return immediately after issuing the command if
zero is specified for
.I wait_response
value.  Other values for
.I wait_response
will give undefined results.
.SH "RETURN VALUES"
Upon succesful completion a value of 0 is returned.
Otherwise, a value of \-1 is returned and
\f4errno\fP
is set to indicate the error.
.SH ERRORS
.PP
.B sam_odlabel(\|)
fails if one or more of the following are true:
.TP 20
.SB ER_BLOCK_SIZE_TOO_LARGE
The specified
.I block_size
is greater than the maximum block size allowed.
.TP
.SB ER_DEVICE_NOT_LABELED
The specified
.I eq_ord
device is not a labeled device.
.TP
.SB ER_DEVICE_NOT_MANUAL_LOAD
The specified
.I eq_ord
device is not a manual load type device.
.TP
.SB ER_DEVICE_NOT_THIS_TYPE
The specified
.I eq_ord
device is not the correct media type.
.TP
.SB ER_FIFO_PATH_LENGTH
The path and filename for the FIFO pipe is too long.
.TP
.SB ER_INVALID_MEDIA_TYPE
Invalid media type specified to be labeled.
.TP
.SB ER_INVALID_U_INFO_LENGTH
.I use_info
must be less than 128 characters in length.
.TP
.SB ER_INVALID_VSN_LENGTH
The specified
.I new_vsn
or
.I old_vsn
is greater than 31 characters in length.
.TP
.SB ER_MEDIA_VSN_NOT_OLD_VSN
The
.I old_vsn
does not match the current VSN on the media.
.TP
.SB ER_NO_EQUIP_ORDINAL
.I eq_ord
is not a defined equipment ordinal in this configuration.
.TP
.SB ER_NO_MASTER_SHM
No Sun StorEdge \%SAM-FS or Sun \%SAM-QFS master shared memory segment defined.
Check that the Sun StorEdge \%SAM-FS or Sun \%SAM-QFS file systems are mounted.
.TP
.SB ER_NO_RESPONSE_FIFO
Unable to create the response FIFO pipe.
.TP
.SB ER_NO_MASTER_SHM_ATT
No Sun StorEdge \%SAM-FS or Sun \%SAM-QFS master shared memory segment found.
Check that the Sun StorEdge \%SAM-FS or Sun \%SAM-QFS file systems are mounted.
.TP
.SB ER_NO_STAT_ROBOT_CATALOG
The robot media changer catalog for equipment ordinal
.I eq_ord
cannot be accessed for status.
.TP
.SB ER_NOT_VALID_SLOT_NUMBER
.I ea
specified is not a valid element address number of the robotic media changer.
.TP
.SB ER_OLD_VSN_NOT_UNK_MEDIA
.I old_vsn
not matching unknown media VSN.
.TP
.SB ER_OPERATOR_NOT_PRIV
Operator does not have permission to label removable media.
.TP
.SB ER_ROBOT_CATALOG_MISSING
No robot catalog was found for equipment ordinal
.I eq_ord
which is defined as a robotic media changer.
.TP
.SB ER_ROBOT_DEVICE_REQUIRED
No devices were found to be defined for equipment ordinal
.I eq_ord
which is defined as a robotic media changer.
.TP
.SB ER_SLOT_NOT_OCCUPIED
No media was found to occupy the element address in the media changer at equipment ordinal
.I eq_ord
.TP
.SB ER_VSN_BARCODE_REQUIRED
.I new_vsn
must be specified. 
.TP
.SB ER_UNABLE_TO_MAP_CATALOG
The catalog for the removable media changer at equipment ordinal
.I eq_ord
is unable to be mapped into memory.
.SH FILES
.TP 20
.SB mcf
The configuration file for Sun StorEdge \%SAM-FS or Sun \%SAM-QFS
environments.
.SH SEE ALSO
.BR odlabel (1M),
.BR tplabel (1M).
.PP
.BR sam_tplabel (3).

