$set 1
31221 Could not take snapshot %s
31222 The prescript %s could not be invoked.\nPlease check that the prescript exists in the correct location and is executable
31223 Snapshot operation incomplete for %s, Compression failed.
31224 The uncompressed size of snapshot %s (%s) differs from previous %d snapshots for file system %s by %s.
31228 The prescript %s failed with error. Please check that the prescript is correct and does not have any errors.\nThe first line of the script must be in this format:\n#! pathname [arg]\nThe ! is essential.
31229 Could not take snapshot %s. Please check that the destination directory for the snapshot exists.
31230 Indexing %s failed.  The snapshot may not be usable.
31231 Could not take snapshot. File system %s is not mounted.\nPlease mount the file system before the next scheduled snapshot
31237 Snapshot %s started
31238 Snapshot %s completed
31247 Could not take snapshot for file system %s. The destination for the snapshot, %s, could not be created or is not a directory.
31248 Snapshot file already exists
31252 See %s for more information.
31253 mail message sent to root
31254 Snapshot for %s already in progress, will not continue.
31255 Could not exec %s: %s
31257 Creation of metadata snapshot %s is completed but the post-snapshot script %s could not be invoked. \nPlease check that the post-snapshot script exists and is executable. You will have to manually run the script at this time.
31258 Creation of metadata snapshot %s is completed but the post-snapshot script %s failed with error. \nPlease check that the post-snapshot script is correct and run it manually at this time.
31263 The time to perform snapshot %s (%.2f hours) differs from previous %d snapshots for file system %s by %.2f hours.
31264 Time to take snapshot %s (%.2f hours) is larger than the interval between scheduled snapshots (%d hours).
31266 %s  removed as directed by retention policy.
31272 The capacity of the file system %s has exceeded the configured high-water mark
