# $Revision: 1.10 $

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

DEPTH = ../../..

include $(DEPTH)/mk/common.mk

MAN_SRCS = intro_libsam.3x \
	sam_archive.3x sam_lstat.3x sam_release.3x sam_segment.3x       \
	sam_setfa.3x sam_stage.3x sam_stat.3x sam_initrpc.3x sam_closerpc.3x

MAN_RELEASED_SRCS = intro_libsam.3x \
	sam_archive.3x sam_closerpc.3x sam_initrpc.3x           \
	sam_release.3x sam_segment.3x sam_setfa.3x sam_stage.3x sam_stat.3x

QFS_RELEASED_SRCS = intro_libsam.3x \
	sam_closerpc.3x sam_initrpc.3x sam_setfa.3x

include $(DEPTH)/mk/targets_man.mk

include $(DEPTH)/mk/depend.mk
