/*
 * Please do not edit this file. It was generated using rpcgen.
 */

/*
 *    SAM-QFS_notice_begin
 *
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at pkg/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 *    SAM-QFS_notice_end
 */

#include <sys/types.h>
#include <sys/time.h>
#include "samrpc.h"

#define	xdr_uint_t xdr_u_int
#define	xdr_ushort_t xdr_u_short

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};


sam_st *
samstat_1(
	statcmd *argp,
	CLIENT *clnt)
{
	static sam_st clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samstat, (xdrproc_t)xdr_statcmd, (caddr_t)argp,
	    (xdrproc_t)xdr_sam_st, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}


sam_st *
samlstat_1(
	statcmd *argp,
	CLIENT * clnt)
{
	static sam_st clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samlstat, (xdrproc_t)xdr_statcmd, (caddr_t)argp,
	    (xdrproc_t)xdr_sam_st, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}


int *
samarchive_1(
	filecmd * argp,
	CLIENT * clnt)
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samarchive, (xdrproc_t)xdr_filecmd, (caddr_t)argp,
	    (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
samsetfa_1(
	filecmd * argp,
	CLIENT * clnt)
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samsetfa, (xdrproc_t)xdr_filecmd, (caddr_t)argp,
	    (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
samsegment_1(
	filecmd *argp,
	CLIENT *clnt)
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samsegment, (xdrproc_t)xdr_filecmd, (caddr_t)argp,
	    (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
samrelease_1(
	filecmd *argp,
	CLIENT *clnt)
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samrelease, (xdrproc_t)xdr_filecmd, (caddr_t)argp,
	    (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
samstage_1(
	filecmd *argp,
	CLIENT *clnt)
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, samstage, (xdrproc_t)xdr_filecmd, (caddr_t)argp,
	    (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
	    TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
