#!/sbin/sh

# $id$

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

. /lib/svc/share/smf_include.sh

if [ ! -d  /opt/SUNWsamfs/sbin ]; then
	echo "The SAM-QFS package is not yet installed."
	echo "The sam-fsd service is being disabled."
	/usr/sbin/svcadm disable svc:/system/sam-fsd
	exit $SMF_EXIT_MON_OFFLINE
fi

SAMFSDCONF=`/opt/SUNWsamfs/sbin/sam-fsd -N 2>/dev/null`
NUMFS=$?
if [ $NUMFS -eq 0 ]; then
	# The decision whether to start sam-fsd is driven by whether or not
	# any SAM-QFS file systems have been configured (via sam-fsd -C).
	# The sam-fsd -N exit code indicates the number that have been
	# configured (0 indicates none).
	echo "SAM-QFS is not yet configured."
	echo "The sam-fsd service is being disabled."
	/usr/sbin/svcadm disable svc:/system/sam-fsd
	exit $SMF_EXIT_MON_OFFLINE
fi

echo "SAM-QFS is configured with" $NUMFS "SAM-QFS file system(s)."
echo "Starting the sam-fsd service."
exec /opt/SUNWsamfs/sbin/sam-fsd -D
