.\" $Revision: 1.8 $
.ds ]W Sun Microsystems
.\" SAM-QFS_notice_begin
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
.\" or https://illumos.org/license/CDDL.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at pkg/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
.\" Use is subject to license terms.
.\"
.\" SAM-QFS_notice_end
.na
.nh
.TH mtf 1 "02 Feb 2006"
.SH NAME
mtf \- make (and check) test files
.SH SYNOPSIS
.B mtf
.RB [ \-B
.IR record_size [ \-number_of_records ]]
.RB [ \-R ]
.RB [ \-S
.IR seed ]
.RB [ \-c ]
.RB [ \-d 
.IR dirname ]
.RB [ \-f ]
.RB [ \-g ]
.RB [ \-i
.IR  b | d | m ]]
.RB [ \-s
.IR minsize [ \-maxsize ]]
.RB [ \-v ]
.IR filename .\|.\|.\|
.SH DESCRIPTION
.B mtf
generates and checks files of random data.  The files consist of records of
of a selectable size.  The default size is 2084 (521 * 4) bytes.
Each record contains the name of the file and
the record number followed by random integers to fill out the record.
In addition, the first record contains the record size,
the random number seed and the data length.  This format allows the file
data to be checked later knowing only the file name.
.LP
The file is written using a selectable buffer size.  The default size is
41 records.  The default buffer and record size values, 41 and 521
(which are prime numbers), avoids performing I/O in integer multiples of
sector and block sizes.
.LP
File names may be generated by using the regular expression "range"
construction [x-y].  When such a filename argument is used, each range
construction, from right to left, is successively incremented.
.LP
For example, the file name
.I "file[A-C][0-9]"
generates the file names
.B fileA0
through
.BR fileC9 .
.LP
Note, you need to "shell escape" the range constructions.
.LP
If
.I filename
is
.BR - ,
file names are read from the standard input.
.LP
If the
.B -R
option is not selected, and one of the files to be generated already exists,
that file name is skipped.
.SH OPTIONS
.TP
.BI \-B " record_size" [ "-number_of_records" ]

Write data in
.I record_size
records.  Use a buffer of
.IR number_of_records * record_size
bytes.  The default record size is 2084, and the default number of records
is 41.
.TP
.B \-R
Allow rewriting of an existing file.
.TP
.BI \-S " seed"
Set the random number seed.
.TP
.B \-c
Read and check files.
.TP
.BI \-d " dirname"
Use
.I dirname
as a prefix to the file names.
.TP
.B \-f
Do not report errors. 
.TP
.B \-g
Generate files.  This is the default action.  To write and check files in
a single step, use both the
.B \-g
and the
.B \-c
options.
.TP
.BI \-i " b | d | m"
Select I/O mode.  The mode is one of the following: 
.I b
buffer I/O;
.I d
"directio" for Solaris 2.5 and above only;
.I m
Memory mapped I/O.
.TP
.BI \-s " size"
Generate file of length
.IR size .
The size may be specified with 'k', 'M', 'G', 'T' multipliers.  e.g. 2.43G.
The default size is 14588 bytes.
.TP
.BI \-s " minsize" [ "-maxsize"]
Generate files with a random length between
.I minsize
and
.IR maxsize .
The default minimum size is 14588 bytes, and the default maximum is the
minimum size.
.TP
.BI \-v
Verbose - print buffer parameters, a \'progress\' bar and timing.
