/*
 * bswap_data.c -- descriptors for byte swapping SAM-QFS data structs
 *
 * This file is temporary; this file will soon, hopefully,
 * be generated automatically.  The structures herein will
 * need to change values when the layout of the structures
 * they describe change.
 */

/*
 *    SAM-QFS_notice_begin
 *
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
 * or https://illumos.org/license/CDDL.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at pkg/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 *    SAM-QFS_notice_end
 */

#ifdef sun
#pragma ident "$Revision: 1.54 $"
#endif

/*
 * Do not edit lines below start comment below.  This file is
 * automatically generated by 'make data' if/when necessary.
 *
 * If this file is out-of-date, then the 'make' of this directory
 * should fail until 'make data' is done.
 */

/* START_DATA */

struct swap_descriptor CatalogEntry_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 44, 4, 1 },
	{ 48, 2, 1 },
	{ 52, 4, 1 },
	{ 56, 8, 2 },
	{ 72, 4, 4 },
	{ 128, 8, 1 },
	{ 136, 4, 1 },
	{ 236, 2, 1 },
	{ 240, 4, 1 },
	{ 376, 0, 0 },
};

struct swap_descriptor CatalogReserve_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 100, 0, 0 },
};

struct swap_descriptor MappedFile_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 0, 0 },
};

struct swap_descriptor csd_filehdr_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 0, 0 },
};

struct swap_descriptor csd_header_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 0, 0 },
};

struct swap_descriptor csd_header_extended_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 8, 10 },
	{ 96, 4, 1 },
	{ 104, 0, 0 },
};

struct swap_descriptor csum_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 0, 0 },
};

struct swap_descriptor rmt_sam_cnt_resp_swap_descriptor[] = {
	{ 32, 4, 1 },
	{ 36, 2, 2 },
	{ 40, 0, 0 },
};

struct swap_descriptor rmt_sam_connect_swap_descriptor[] = {
	{ 32, 0, 0 },
};

struct swap_descriptor rmt_sam_req_resp_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 0, 0 },
};

struct swap_descriptor rmt_sam_request_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 8, 1 },
	{ 16, 4, 1 },
	{ 20, 2, 1 },
	{ 424, 0, 0 },
};

struct swap_descriptor rmt_sam_update_vsn_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 8, 4, 1 },
	{ 52, 4, 1 },
	{ 56, 2, 1 },
	{ 60, 4, 1 },
	{ 64, 8, 2 },
	{ 80, 4, 4 },
	{ 136, 8, 1 },
	{ 144, 4, 1 },
	{ 244, 2, 1 },
	{ 248, 4, 1 },
	{ 384, 4, 1 },
	{ 392, 0, 0 },
};

struct swap_descriptor rmt_sam_vsn_entry_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 44, 4, 1 },
	{ 48, 2, 1 },
	{ 52, 4, 1 },
	{ 56, 8, 2 },
	{ 72, 4, 4 },
	{ 128, 8, 1 },
	{ 136, 4, 1 },
	{ 236, 2, 1 },
	{ 240, 4, 1 },
	{ 376, 4, 1 },
	{ 384, 0, 0 },
};

struct swap_descriptor sam_acl_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 2, 1 },
	{ 12, 0, 0 },
};

struct swap_descriptor sam_acl_inode_swap_descriptor[] = {
	{ 0, 4, 8 },
	{ 32, 2, 1 },
	{ 36, 4, 2 },
	{ 44, 2, 1 },
	{ 48, 4, 2 },
	{ 56, 2, 1 },
	{ 60, 4, 2 },
	{ 68, 2, 1 },
	{ 72, 4, 2 },
	{ 80, 2, 1 },
	{ 84, 4, 2 },
	{ 92, 2, 1 },
	{ 96, 4, 2 },
	{ 104, 2, 1 },
	{ 108, 4, 2 },
	{ 116, 2, 1 },
	{ 120, 4, 2 },
	{ 128, 2, 1 },
	{ 132, 4, 2 },
	{ 140, 2, 1 },
	{ 144, 4, 2 },
	{ 152, 2, 1 },
	{ 156, 4, 2 },
	{ 164, 2, 1 },
	{ 168, 4, 2 },
	{ 176, 2, 1 },
	{ 180, 4, 2 },
	{ 188, 2, 1 },
	{ 192, 4, 2 },
	{ 200, 2, 1 },
	{ 204, 4, 2 },
	{ 212, 2, 1 },
	{ 216, 4, 2 },
	{ 224, 2, 1 },
	{ 228, 4, 2 },
	{ 236, 2, 1 },
	{ 240, 4, 2 },
	{ 248, 2, 1 },
	{ 252, 4, 2 },
	{ 260, 2, 1 },
	{ 264, 4, 2 },
	{ 272, 2, 1 },
	{ 276, 4, 2 },
	{ 284, 2, 1 },
	{ 288, 4, 2 },
	{ 296, 2, 1 },
	{ 300, 4, 2 },
	{ 308, 2, 1 },
	{ 312, 4, 2 },
	{ 320, 2, 1 },
	{ 324, 4, 2 },
	{ 332, 2, 1 },
	{ 336, 4, 2 },
	{ 344, 2, 1 },
	{ 348, 4, 2 },
	{ 356, 2, 1 },
	{ 360, 4, 2 },
	{ 368, 2, 1 },
	{ 372, 4, 2 },
	{ 380, 2, 1 },
	{ 384, 4, 2 },
	{ 392, 2, 1 },
	{ 396, 4, 2 },
	{ 404, 2, 1 },
	{ 408, 4, 2 },
	{ 416, 2, 1 },
	{ 420, 4, 2 },
	{ 428, 2, 1 },
	{ 432, 4, 2 },
	{ 440, 2, 1 },
	{ 444, 4, 2 },
	{ 452, 2, 1 },
	{ 456, 4, 2 },
	{ 464, 2, 1 },
	{ 468, 4, 2 },
	{ 476, 2, 1 },
	{ 480, 0, 0 },
};

struct swap_descriptor sam_arch_inode_swap_descriptor[] = {
	{ 2, 2, 1 },
	{ 4, 4, 5 },
	{ 58, 2, 1 },
	{ 60, 4, 5 },
	{ 114, 2, 1 },
	{ 116, 4, 5 },
	{ 170, 2, 1 },
	{ 172, 4, 5 },
	{ 224, 0, 0 },
};

struct swap_descriptor sam_arch_rminfo_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 2, 2 },
	{ 12, 4, 3 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_archive_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 2, 2 },
	{ 12, 4, 4 },
	{ 28, 2, 1 },
	{ 64, 4, 2 },
	{ 104, 0, 0 },
};

struct swap_descriptor sam_archive_info_swap_descriptor[] = {
	{ 2, 2, 1 },
	{ 4, 4, 5 },
	{ 56, 0, 0 },
};

struct swap_descriptor sam_block_fgetbuf_swap_descriptor[] = {
	{ 0, 8, 2 },
	{ 16, 4, 2 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_block_getbuf_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 8, 2 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_block_getino_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 8, 2 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_block_quota_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 8, 1 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_block_sblk_swap_descriptor[] = {
	{ 0, 8, 2 },
	{ 16, 0, 0 },
};

struct swap_descriptor sam_block_vfsstat_swap_descriptor[] = {
	{ 0, 8, 12 },
	{ 96, 0, 0 },
};

struct swap_descriptor sam_block_vfsstat_v2_swap_descriptor[] = {
	{ 0, 8, 4 },
	{ 32, 2, 2 },
	{ 36, 4, 1 },
	{ 40, 8, 7 },
	{ 96, 0, 0 },
};

struct swap_descriptor sam_callout_relinquish_lease_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 4, 4, 1 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_callout_stage_swap_descriptor[] = {
	{ 4, 4, 2 },
	{ 16, 0, 0 },
};

struct swap_descriptor sam_cl_attr_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 4, 2, 1 },
	{ 8, 4, 1 },
	{ 16, 8, 1 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_cred_swap_descriptor[] = {
	{ 0, 4, 25 },
	{ 104, 0, 0 },
};

struct swap_descriptor sam_di_osd_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 8, 8 },
	{ 88, 0, 0 },
};

struct swap_descriptor sam_dirent_swap_descriptor[] = {
	{ 0, 2, 2 },
	{ 4, 4, 2 },
	{ 12, 2, 2 },
	{ 20, 0, 0 },
};

struct swap_descriptor sam_disk_inode_swap_descriptor[] = {
	{ 0, 4, 6 },
	{ 24, 8, 1 },
	{ 32, 2, 2 },
	{ 36, 4, 18 },
	{ 118, 2, 4 },
	{ 128, 4, 23 },
	{ 240, 0, 0 },
};

struct swap_descriptor sam_disk_inode_part2_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 16, 4, 1 },
	{ 24, 4, 2 },
	{ 32, 0, 0 },
};

struct swap_descriptor sam_dquot_swap_descriptor[] = {
	{ 0, 8, 12 },
	{ 96, 4, 4 },
	{ 112, 8, 2 },
	{ 128, 0, 0 },
};

struct swap_descriptor sam_hlp_inode_swap_descriptor[] = {
	{ 0, 4, 120 },
	{ 480, 0, 0 },
};

struct swap_descriptor sam_host_table_swap_descriptor[] = {
	{ 0, 4, 5 },
	{ 20, 2, 2 },
	{ 24, 4, 1 },
	{ 28, 2, 2 },
	{ 36, 0, 0 },
};

struct swap_descriptor sam_id_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_indirect_extent_swap_descriptor[] = {
	{ 0, 4, 2048 },
	{ 10240, 4, 4 },
	{ 10256, 0, 0 },
};

struct swap_descriptor sam_ino_instance_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 4, 2 },
	{ 16, 0, 0 },
};

struct swap_descriptor sam_ino_record_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 4, 2 },
	{ 16, 2, 2 },
	{ 20, 4, 1 },
	{ 24, 8, 4 },
	{ 56, 4, 6 },
	{ 80, 8, 1 },
	{ 88, 2, 2 },
	{ 92, 4, 18 },
	{ 174, 2, 4 },
	{ 184, 4, 23 },
	{ 296, 4, 2 },
	{ 312, 4, 1 },
	{ 320, 4, 2 },
	{ 328, 0, 0 },
};

struct swap_descriptor sam_inode_ext_hdr_swap_descriptor[] = {
	{ 0, 4, 8 },
	{ 32, 0, 0 },
};

struct swap_descriptor sam_inode_quota_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 8, 12 },
	{ 112, 4, 4 },
	{ 128, 8, 2 },
	{ 144, 0, 0 },
};

struct swap_descriptor sam_inode_samaid_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_inode_samarch_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 4, 2, 2 },
	{ 48, 0, 0 },
};

struct swap_descriptor sam_inode_samattr_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 136, 0, 0 },
};

struct swap_descriptor sam_inode_setattr_swap_descriptor[] = {
	{ 0, 8, 5 },
	{ 40, 4, 13 },
	{ 96, 4, 1 },
	{ 104, 0, 0 },
};

struct swap_descriptor sam_inode_stage_swap_descriptor[] = {
	{ 8, 8, 1 },
	{ 16, 0, 0 },
};

struct swap_descriptor sam_label_swap_descriptor[] = {
	{ 4, 4, 6 },
	{ 284, 0, 0 },
};

struct swap_descriptor sam_lease_data_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 4, 4, 1 },
	{ 8, 8, 5 },
	{ 48, 2, 2 },
	{ 52, 4, 1 },
	{ 60, 4, 3 },
	{ 72, 0, 0 },
};

struct swap_descriptor sam_mva_inode_swap_descriptor[] = {
	{ 0, 4, 7 },
	{ 64, 8, 3 },
	{ 120, 8, 3 },
	{ 176, 8, 3 },
	{ 232, 8, 3 },
	{ 288, 8, 3 },
	{ 344, 8, 3 },
	{ 400, 8, 3 },
	{ 456, 8, 3 },
	{ 480, 0, 0 },
};

struct swap_descriptor sam_name_acl_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 0, 0 },
};

struct swap_descriptor sam_name_create_swap_descriptor[] = {
	{ 0, 8, 5 },
	{ 40, 4, 13 },
	{ 96, 4, 3 },
	{ 112, 0, 0 },
};

struct swap_descriptor sam_name_link_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_name_lookup_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 16, 0, 0 },
};

struct swap_descriptor sam_name_mkdir_swap_descriptor[] = {
	{ 0, 8, 5 },
	{ 40, 4, 13 },
	{ 96, 0, 0 },
};

struct swap_descriptor sam_name_remove_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_name_rename_swap_descriptor[] = {
	{ 0, 4, 8 },
	{ 32, 0, 0 },
};

struct swap_descriptor sam_name_rmdir_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_name_symlink_swap_descriptor[] = {
	{ 0, 8, 5 },
	{ 40, 4, 13 },
	{ 96, 4, 2 },
	{ 104, 0, 0 },
};

struct swap_descriptor sam_notify_dnlc_swap_descriptor[] = {
	{ 256, 0, 0 },
};

struct swap_descriptor sam_notify_lease_swap_descriptor[] = {
	{ 0, 4, 1 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_old_arch_rminfo_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 2, 2 },
	{ 12, 4, 3 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_old_archive_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 2, 2 },
	{ 12, 4, 4 },
	{ 28, 2, 1 },
	{ 64, 4, 2 },
	{ 104, 0, 0 },
};

struct swap_descriptor sam_old_resource_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 8, 8, 1 },
	{ 16, 2, 2 },
	{ 20, 4, 4 },
	{ 36, 2, 1 },
	{ 72, 4, 2 },
	{ 176, 4, 1 },
	{ 408, 0, 0 },
};

struct swap_descriptor sam_old_resource_file_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 8, 8, 1 },
	{ 16, 2, 2 },
	{ 20, 4, 4 },
	{ 36, 2, 1 },
	{ 72, 4, 2 },
	{ 176, 4, 1 },
	{ 408, 4, 2 },
	{ 448, 0, 0 },
};

struct swap_descriptor sam_old_rminfo_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 8, 4, 2 },
	{ 16, 8, 2 },
	{ 64, 4, 1 },
	{ 292, 2, 2 },
	{ 328, 8, 3 },
	{ 384, 8, 3 },
	{ 440, 8, 3 },
	{ 496, 8, 3 },
	{ 552, 8, 3 },
	{ 608, 8, 3 },
	{ 664, 8, 3 },
	{ 720, 8, 3 },
	{ 744, 0, 0 },
};

struct swap_descriptor sam_old_section_swap_descriptor[] = {
	{ 32, 8, 3 },
	{ 56, 0, 0 },
};

struct swap_descriptor sam_osd_ext_inode_swap_descriptor[] = {
	{ 0, 8, 48 },
	{ 384, 2, 48 },
	{ 480, 0, 0 },
};

struct swap_descriptor sam_perm_inode_swap_descriptor[] = {
	{ 0, 4, 6 },
	{ 24, 8, 1 },
	{ 32, 2, 2 },
	{ 36, 4, 18 },
	{ 118, 2, 4 },
	{ 128, 4, 23 },
	{ 240, 4, 4 },
	{ 258, 2, 1 },
	{ 260, 4, 5 },
	{ 314, 2, 1 },
	{ 316, 4, 5 },
	{ 370, 2, 1 },
	{ 372, 4, 5 },
	{ 426, 2, 1 },
	{ 428, 4, 5 },
	{ 480, 4, 2 },
	{ 496, 4, 1 },
	{ 504, 4, 2 },
	{ 512, 0, 0 },
};

struct swap_descriptor sam_perm_inode_v1_swap_descriptor[] = {
	{ 0, 4, 6 },
	{ 24, 8, 1 },
	{ 32, 2, 2 },
	{ 36, 4, 18 },
	{ 118, 2, 4 },
	{ 128, 4, 23 },
	{ 240, 4, 4 },
	{ 258, 2, 1 },
	{ 260, 4, 5 },
	{ 314, 2, 1 },
	{ 316, 4, 5 },
	{ 370, 2, 1 },
	{ 372, 4, 5 },
	{ 426, 2, 1 },
	{ 428, 4, 5 },
	{ 480, 4, 8 },
	{ 512, 0, 0 },
};

struct swap_descriptor sam_quota_group_swap_descriptor[] = {
	{ 0, 8, 3 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_quota_group_pair_swap_descriptor[] = {
	{ 0, 8, 6 },
	{ 48, 0, 0 },
};

struct swap_descriptor sam_resource_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 8, 8, 1 },
	{ 16, 2, 2 },
	{ 20, 4, 4 },
	{ 36, 2, 1 },
	{ 72, 4, 2 },
	{ 176, 4, 1 },
	{ 408, 0, 0 },
};

struct swap_descriptor sam_resource_file_swap_descriptor[] = {
	{ 0, 2, 1 },
	{ 8, 8, 1 },
	{ 16, 2, 2 },
	{ 20, 4, 4 },
	{ 36, 2, 1 },
	{ 72, 4, 2 },
	{ 176, 4, 1 },
	{ 408, 4, 2 },
	{ 448, 8, 3 },
	{ 472, 0, 0 },
};

struct swap_descriptor sam_rfa_inode_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 2, 1 },
	{ 16, 8, 1 },
	{ 24, 2, 2 },
	{ 28, 4, 4 },
	{ 44, 2, 1 },
	{ 80, 4, 2 },
	{ 184, 4, 1 },
	{ 416, 4, 2 },
	{ 456, 8, 3 },
	{ 480, 0, 0 },
};

struct swap_descriptor sam_rm_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 2, 2 },
	{ 12, 4, 3 },
	{ 24, 0, 0 },
};

struct swap_descriptor sam_san_block_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 112, 0, 0 },
};

struct swap_descriptor sam_san_callout_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 24, 8, 1 },
	{ 32, 4, 2 },
	{ 40, 2, 2 },
	{ 44, 4, 1 },
	{ 48, 8, 4 },
	{ 80, 4, 6 },
	{ 104, 8, 1 },
	{ 112, 2, 2 },
	{ 116, 4, 18 },
	{ 198, 2, 4 },
	{ 208, 4, 23 },
	{ 320, 4, 2 },
	{ 336, 4, 1 },
	{ 344, 4, 2 },
	{ 352, 0, 0 },
};

struct swap_descriptor sam_san_header_swap_descriptor[] = {
	{ 0, 8, 1 },
	{ 8, 2, 1 },
	{ 12, 2, 4 },
	{ 20, 4, 8 },
	{ 56, 0, 0 },
};

struct swap_descriptor sam_san_inode_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 2, 1 },
	{ 16, 4, 1 },
	{ 24, 8, 1 },
	{ 176, 4, 25 },
	{ 280, 0, 0 },
};

struct swap_descriptor sam_san_inode2_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 2, 1 },
	{ 16, 4, 1 },
	{ 24, 8, 1 },
	{ 176, 4, 25 },
	{ 280, 8, 1 },
	{ 288, 4, 2 },
	{ 296, 2, 2 },
	{ 300, 4, 1 },
	{ 304, 8, 4 },
	{ 336, 4, 6 },
	{ 360, 8, 1 },
	{ 368, 2, 2 },
	{ 372, 4, 18 },
	{ 454, 2, 4 },
	{ 464, 4, 23 },
	{ 576, 4, 2 },
	{ 592, 4, 1 },
	{ 600, 4, 2 },
	{ 608, 0, 0 },
};

struct swap_descriptor sam_san_lease_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 2, 1 },
	{ 16, 4, 1 },
	{ 24, 8, 1 },
	{ 32, 2, 1 },
	{ 36, 4, 1 },
	{ 40, 8, 5 },
	{ 80, 2, 2 },
	{ 84, 4, 1 },
	{ 92, 4, 3 },
	{ 104, 2, 2 },
	{ 112, 8, 2 },
	{ 128, 4, 27 },
	{ 240, 4, 10 },
	{ 280, 0, 0 },
};

struct swap_descriptor sam_san_lease2_swap_descriptor[] = {
	{ 0, 4, 3 },
	{ 12, 2, 1 },
	{ 16, 4, 1 },
	{ 24, 8, 1 },
	{ 32, 2, 1 },
	{ 36, 4, 1 },
	{ 40, 8, 5 },
	{ 80, 2, 2 },
	{ 84, 4, 1 },
	{ 92, 4, 3 },
	{ 104, 2, 2 },
	{ 112, 8, 2 },
	{ 128, 4, 27 },
	{ 240, 4, 10 },
	{ 280, 2, 1 },
	{ 288, 8, 1 },
	{ 296, 4, 2 },
	{ 304, 2, 2 },
	{ 308, 4, 1 },
	{ 312, 8, 4 },
	{ 344, 4, 6 },
	{ 368, 8, 1 },
	{ 376, 2, 2 },
	{ 380, 4, 18 },
	{ 462, 2, 4 },
	{ 472, 4, 23 },
	{ 584, 4, 2 },
	{ 600, 4, 1 },
	{ 608, 4, 2 },
	{ 616, 0, 0 },
};

struct swap_descriptor sam_san_mount_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 168, 4, 4 },
	{ 188, 0, 0 },
};

struct swap_descriptor sam_san_name_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 120, 4, 25 },
	{ 232, 0, 0 },
};

struct swap_descriptor sam_san_name2_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 16, 8, 1 },
	{ 24, 4, 2 },
	{ 32, 2, 2 },
	{ 36, 4, 1 },
	{ 40, 8, 4 },
	{ 72, 4, 6 },
	{ 96, 8, 1 },
	{ 104, 2, 2 },
	{ 108, 4, 18 },
	{ 190, 2, 4 },
	{ 200, 4, 23 },
	{ 312, 4, 2 },
	{ 328, 4, 1 },
	{ 336, 4, 2 },
	{ 344, 8, 1 },
	{ 352, 4, 2 },
	{ 360, 2, 2 },
	{ 364, 4, 1 },
	{ 368, 8, 4 },
	{ 400, 4, 6 },
	{ 424, 8, 1 },
	{ 432, 2, 2 },
	{ 436, 4, 18 },
	{ 518, 2, 4 },
	{ 528, 4, 23 },
	{ 640, 4, 2 },
	{ 656, 4, 1 },
	{ 664, 4, 2 },
	{ 792, 0, 0 },
};

struct swap_descriptor sam_san_notify_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 264, 0, 0 },
};

struct swap_descriptor sam_sbinfo_swap_descriptor[] = {
	{ 4, 4, 3 },
	{ 48, 4, 2 },
	{ 56, 8, 5 },
	{ 96, 2, 2 },
	{ 100, 4, 2 },
	{ 108, 2, 2 },
	{ 112, 8, 2 },
	{ 128, 2, 4 },
	{ 136, 8, 1 },
	{ 144, 4, 2 },
	{ 152, 2, 2 },
	{ 156, 4, 2 },
	{ 164, 2, 2 },
	{ 168, 4, 1 },
	{ 172, 2, 2 },
	{ 176, 8, 1 },
	{ 184, 4, 1 },
	{ 188, 2, 1 },
	{ 192, 4, 1 },
	{ 256, 0, 0 },
};

struct swap_descriptor sam_sbord_swap_descriptor[] = {
	{ 0, 2, 2 },
	{ 6, 2, 1 },
	{ 8, 8, 3 },
	{ 32, 4, 2 },
	{ 40, 8, 2 },
	{ 56, 4, 1 },
	{ 60, 2, 2 },
	{ 64, 0, 0 },
};

struct swap_descriptor sam_share_flock_swap_descriptor[] = {
	{ 0, 2, 2 },
	{ 8, 8, 2 },
	{ 24, 4, 2 },
	{ 32, 0, 0 },
};

struct swap_descriptor sam_sln_inode_swap_descriptor[] = {
	{ 0, 4, 4 },
	{ 480, 0, 0 },
};

struct swap_descriptor sam_sr_attr_swap_descriptor[] = {
	{ 0, 2, 2 },
	{ 4, 4, 1 },
	{ 8, 8, 4 },
	{ 40, 0, 0 },
};

struct swap_descriptor sam_timestruc_swap_descriptor[] = {
	{ 0, 4, 2 },
	{ 8, 0, 0 },
};

struct swap_descriptor sam_vattr_swap_descriptor[] = {
	{ 0, 8, 5 },
	{ 40, 4, 13 },
	{ 96, 0, 0 },
};

struct swap_descriptor sam_vsn_array_swap_descriptor[] = {
	{ 32, 8, 3 },
	{ 88, 8, 3 },
	{ 144, 8, 3 },
	{ 200, 8, 3 },
	{ 256, 8, 3 },
	{ 312, 8, 3 },
	{ 368, 8, 3 },
	{ 424, 8, 3 },
	{ 448, 0, 0 },
};

struct swap_descriptor sam_vsn_section_swap_descriptor[] = {
	{ 32, 8, 3 },
	{ 56, 0, 0 },
};
