# $Revision: 1.10 $

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

DEPTH = ../../..

include $(DEPTH)/mk/common.mk

# Keep the entries in the following lines in alphabetical order, please.
MAN_SRCS =  acl2640.7 acl452.7 grauaci.7 \
	historian.7 ibm3584.7 ibm3494.7 sam-remote.7 samst.7 stk.7 ssi.sh.7 \
	ssi_so.7 sony.7

MAN_RELEASED_SRCS =  acl2640.7 acl452.7 grauaci.7 \
	historian.7 ibm3584.7 ibm3494.7 samst.7 sony.7 stk.7 ssi.sh.7 ssi_so.7

REM_RELEASED_SRCS =  sam-remote.7

include $(DEPTH)/mk/targets_man.mk

include $(DEPTH)/mk/depend.mk
