.\" $Revision: 1.18 $
.ds ]W Sun Microsystems
.\" SAM-QFS_notice_begin
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
.\" or https://illumos.org/license/CDDL.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at pkg/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
.\" Use is subject to license terms.
.\"
.\" SAM-QFS_notice_end
.TH sam-arcopy 8 "20 Sep 20026"
.SH NAME
sam-arcopy \- Sun StorEdge \%SAM-FS and Sun \%SAM-QFS archive copy daemon
.SH SYNOPSIS
.B /opt/SUNWsamfs/sbin/sam-arcopy 
.SH AVAILABILITY
.LP
SUNWsamfs
.SH DESCRIPTION
The
.B sam-arcopy
process is responsible for copying Sun StorEdge \%SAM-FS
or Sun \%SAM-QFS
files to removable media.  It is executed by
.BR sam-archiverd (8).
All required information is transmitted to the
.B sam-arcopy
in memory mapped files.
.SH SEE ALSO
.BR sam-archiverd (8)

