#!/bin/ksh

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or https://illumos.org/license/CDDL.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

#
# config - start or send a HUP to sam-fsd to cause (re)configuration of
# file systems.
#
#	$Revision: 1.11 $

#
# Return pid(s) of named process(es) in variable "pid"
# The variable pid should be treated as a list of 0 or more process id's
# because if there are is than one process with the same name, there
# will be more than one process id's.
#
pidproc() {
	pid=`/bin/ps ax |
		/usr/bin/awk '{print $1 " " $5}' |
		/bin/sed -e 's/\/.*\///' |
		/bin/grep " ${1}$" |
		/usr/bin/awk '{print $1}'`
}

case "$1" in

'config')

	pidproc sam-fsd
	echo "Configuring SAM-FS"
	/opt/SUNWsamfs/util/check_mcf.pl update
	if [ "${pid}" = "" ]; then
		/opt/SUNWsamfs/sbin/sam-fsd -C
		sleep 5
		/opt/SUNWsamfs/sbin/sam-fsd > /dev/null
		sleep 2
		pidproc sam-fsd
	fi
	if [ "${pid}" = "" ]; then
		echo "Failed to start sam-fsd; check logs and inittab"
		exit 1
	fi
	kill -HUP ${pid}
	sleep 2
	/opt/SUNWsamfs/sbin/sam-fsd > /dev/null
	;;

*)
	echo "Usage: $0 config"
	exit 1
	;;
esac
exit 0
