# $Revision: 1.12 $

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or https://illumos.org/license/CDDL.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

DEPTH = ../../..

include $(DEPTH)/mk/common.mk

MAN_SRCS = \
	alterfile.1 \
	archive.1 \
	schproj.1 \
	dvt.1 \
	genfile.1 \
	pdvt.1 \
	release.1 \
	request.1        \
	sdu.1 \
	segment.1 \
	setfa.1 \
	sfind.1 \
	sls.1 \
	squota.1 \
	ssum.1 \
	stage.1

MAN_RELEASED_SRCS = \
	archive.1 \
	schproj.1 \
	release.1 \
	request.1 \
	sdu.1 \
	segment.1 \
	setfa.1   \
	sfind.1 \
	sls.1 \
	squota.1 \
	ssum.1 \
	stage.1

QFS_RELEASED_SRCS = \
	schproj.1 \
	setfa.1 \
	sfind.1 \
	sls.1

include $(DEPTH)/mk/targets_man.mk

include $(DEPTH)/mk/depend.mk
