#ifndef lint
static char SccsId[] = "@(#)td_main.c           2.0 1/10/94 ";
#endif
/*
 * Copyright (1993, 2011) Oracle and/or its affiliates.  All rights reserved.
 *
 * Name:
 *      td_main
 *
 * Description:
 *      The main function for trace_decode, the trace decoder takes
 *      the acsss_trace.log file generated by the CSI/SSI as input, and
 *      outputs a human readable version of the input data.
 *      It will accept as input the following syntax:
 *
 *      trace_decode [-s] [-a] < infile > outfile
 *
 *      where -s specifies the short output format
 *               (the default is long format)
 *            -a specifies ADI protocol
 *
 * Return Value:
 *      NONE
 *
 * Implicit Inputs:
 *      td_output_format, td_adi_protocol.
 *
 * Implicit Outputs:
 *      td_output_format, td_adi_protocol.
 *
 * Considerations:
 *      NONE
 *
 * Revision History:
 *
 *      M. H. Shum          10-Sep-1993     Original.
 *      K. J. Stickney      23-Dec-1994     Changes for Solaris.
 *      Anton Vatcky        01-Mar-2002     Removed prototype of getopt for
 *                                          Solaris and AIX.
 *      Hemendra            06-Jan-2003     Removed prototype for getopt
 *                                          for Linux.
 *      Joseph Nofi         15-Aug-2011     XAPI support;
*                                           Added td_packet_id and td_packet_header
 *                                          global variables.
 *                                          Added -c (compare) option to produce
 *                                          results suitable for unix diff command
 *                                          comparison.
 *
 */


/* 
 * header files
 */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "td.h"

/*
 * global variables
 */
char td_msg_buf[MAX_MESSAGE_SIZE];     /* binary data buffer */
char td_ascii_buf[MAX_MESSAGE_SIZE*2]; /* raw ascii data buffer */
PACKET_TYPE  td_packet_type;           /* REQUEST/RESPONSE/ACK */
FORMAT td_output_format;               /* LONG/SHORT format */
PACKET_HEADER  td_packet_header;       /* CSI/ADI/IPC */
int  td_adi_protocol;                  /* TRUE=ADI, FALSE=RPC */
unsigned char td_mopts;                /* message options */
unsigned long td_xopts;                /* extended options */
char *td_msg_ptr;                      /* pointer to td_msg_buf */
char *td_fix_portion = "  Fixed Portion:\n";
char *td_var_portion = "\n  Variable Portion:\n";
unsigned short td_packet_id;           /* packet id */

/* prototypes */
#ifdef SOLARIS
#elif AIX
#elif LINUX
#else
int getopt(int, char * *, char *);
#endif

/*
 * The main function of csi_trace_decode
 */
int main (int argc, char **argv)
{
    int c;

    td_output_format = LONG;    /* default to long version */
    td_adi_protocol = FALSE;    /* default to RPC  */

    /*****************************************************************/
    /* Check the command line arguments:                             */
    /* -c results in output that is suitable for comparison to       */
    /*    other trace_decode files produced with the -c option as    */
    /*    it elimiates the date, IPC_HEADER, CSI_HEADER and          */
    /*    buffer displays.                                           */
    /*****************************************************************/
    while ((c = getopt(argc, argv, "sca")) != -1)
    {
        switch (c)
        {
        case 's':
            td_output_format = SHORT;
            break;
        case 'c':
            td_output_format = COMPARE;
            break;
        case 'a':
            td_adi_protocol = TRUE;
            break;
        default:
            fputs("Usage: trace_decode [-s] [-c] [-a] < infile\n", stderr);
        }
    }

    /* get packet and decode them */ 
    td_get_packet();

    return 0;
}








