static char SccsId[] = "@(#)cl_ipc_creat.c	1.1 1/10/94 (c) 1989-1994 STK";
/*
 * Copyright (C) 1988,2010, Oracle and/or its affiliates. All rights reserved.
 *
 * Name:
 *
 *      cl_ipc_create
 *
 * Description:
 *
 *      Common routine for setting up the process IPC environment.  Creates an
 *      input socket and binds the passed socket name to it.  Establishes a
 *      queue for retaining outgoing messages in case of incoming messages or
 *      a connection failure.
 *
 *        o Check the length of the socket name.  Return STATUS_INVALID_VALUE
 *          if no name is passed or the name is greater than SOCKET_NAME_SIZE
 *          characters long.
 *
 *        o Check sd_in (global variable) to determine if socket previously
 *          opened.  If greater than or equal to zero, the socket is open
 *          (probably result of fork from parent process):
 *
 *            - Check small_preamble (global) to determine if shared memory
 *              segment is attached.  If non-zero, detach shared memory and
 *              ignore any errors.  (done only if IPC_SHARED is defined)
 *
 *            - Close the descriptor in sd_in and set it to -1.  This prevents
 *              IPC writes on a bad file descriptor.
 *
 *        o If using shared memory IPC mechanism, attach to the shared memory
 *          segment.  Log an event and return STATUS_IPC_FAILURE if unable to
 *          attach to shared memory.  We attach to shared memory first because
 *          it's easier to get rid of on a subsequent error.
 *
 *        o Create input socket.  Log an event, detach from shared memory (if
 *          necessary) and return STATUS_IPC_FAILURE if unable to create a
 *          socket.
 *
 *        o If using an internet stream socket IPC mechanism, set the maximum
 *          length of the queue for pending connections to MAX_CONNECTIONS.  
 *          If an error occurs, log an event and return STATUS_IPC_FAILURE.
 *
 *        o Initialize the fd_list (global) descriptor array with the input 
 *          socket descriptor.  The array is used in checking for input on
 *          file descriptors before writing outgoing messages on the socket.
 *
 *        o Check cl_write_q (global) to determine if the write queue was
 *          previously created.  If non-zero, delete the previous queue and
 *          disregard any errors.  A previously-existing queue is the result
 *          of a fork from a parent process.  Since the queue is a duplicate
 *          of the parent, reusing the queue could result in the child sending
 *          duplicate messages.
 *
 *        o Create a queue for retaining outgoing IPC messages when incoming
 *          messages are present on the socket.  If an error occurs, log an
 *          event and return STATUS_IPC_FAILURE.
 *
 *        o Set the maximum retry count (max_retries) based on CSI environment
 *          variables.
 *
 *        o Return STATUS_SUCCESS.
 *
 * Return Values:
 *
 *      STATUS_SUCCESS
 *      STATUS_INVALID_VALUE    sock_name not [1..SOCKET_NAME_SIZE] chars long.
 *      STATUS_IPC_FAILURE      Unable to create socket descriptor or attach to
 *                              shared memory.
 *
 * Implicit Inputs:
 *
 *      NONE
 *
 * Implicit Outputs:
 *
 *      cl_write_q      IPC output message queue:
 *                        = 0 if queue not yet created,
 *                        > 0 if queue previously created.
 *      fd_list         Input descriptor array.
 *      max_retries     Maximum number of retries based on CSI variables.
 *      my_sock_name    Input socket name (possibly generated by cl_ipc_open).
 *      n_fds           Number of descriptors in fd_list.
 *      sd_in           IPC input socket descriptor:
 *                        <  0 if socket not created or open,
 *                        >= 0 if socket open and ready to use.
 *      small_preamble  Pointer to beginning address of shared memory segment:
 *                        =  0 if segment not attached,
 *                        != 0 if segment attached.
 *
 * Considerations:
 *
 *      A shared memory IPC mechanism is used when IPC_SHARED is defined.
 *      Otherwise an internet stream socket is used.
 *      
 *      When DEBUG is defined, cl_get_sockname is invoked to remap "well-known"
 *      socket names from environment variables (if defined).  This is done to
 *      support multiple development and test environments on the same platform.
 *
 *      It's advisable to flush the write queue (via cl_ipc_send) prior to 
 *      forking a child process to avoid the possiblility of duplicate messages
 *      being sent.
 *
 *      It's also advisable to detach from shared memory and close sd_in prior
 *      exec'ing a program.  If the exec is successful, the context of sd_in
 *      and small_preamble is lost.  This may cause the process to attach to
 *      shared memory a second time which is a problem on Ultrix systems.
 *
 * Module Test Plan:
 *
 *      Verified in ut_ipc_check.
 *
 * Revision History:
 *
 *      D. F. Reed              27-Sep-1988     Original.
 *
 *      D. F. Reed              14-Mar-1989     Modified to support internet
 *          socket usage.  Calls cl_ipc_open() to actually create/bind socket.
 *          If the string "0" is passed in as the socket name, the socket name
 *          (port) is picked by cl_ipc_open() and returned.
 *
 *      J. Montgomery           03-May-1989     Added Write Queue initialization
 *
 *      D. F. Reed              23-May-1989     Modified to support multiple
 *          input descriptor checking.
 *
 *      D. L. Trachy            12-Jun-1990     Added shared memory IPC
 *          mechanism.
 *
 *      D. A. Beidle            23-Jul-1990     Close sd_in if non-zero before
 *          creating a new socket.
 *
 *      D. A. Beidle            28-Sep-1991     Moved alternate socket name
 *          selection to cl_get_sockname().  Removed prior history on addition
 *          of "well-known" socket names.  Lint cleanup.
 *
 *      D. A. Beidle            24-Nov-1991.    IBR#151 - Check for sd_in >= 0
 *          to determine if socket previously opened.  Detach shared memory if
 *          socket previously opened.  Destroy output queue if queue previosly
 *          created.  Added comments regarding use with child processes.
 *
 *      E. A. Alongi            02-Dec-1992     Added missing #ifdef IPC_SHARED/
 *          #endif pair directives around shmdt() function call.
 *      E. A. Alongi            04-Oct-1993.    Replaced getenv() calls with
 *	    dv_get_number() when accessing CSI timeout and retry variables.
 *	    Also changed the local varibles used as args from ints to longs.
 *	    Eliminated include file stdlib.h.
 *	H. I. Grapek		04-Jan-1994	Added NOT_CSC for ML.
 *	K. J. Stickney		23-Dec-1994	Added ifdef for solaris
 *                                              that sets MAX_CONNECTIONS
 *                                              to 5. Makes calls to
 *                                              listen() have larger queue
 *                                              value.
 *	Mitch Black		31-Jan-2004	Set MAX_CONNECTIONS to a 
 *						higher value for Linux
 *	Mitch Black		17-Nov-2004	Set MAX_CONNECTIONS to take 
 *		advantage of longer "listen()" queues on all target OS's
 *      Mitch Black     28-Feb-2005     Changed listen queue to use greater of
 *					SOMAXCONN or 32, since some OS's
 *                                      define SOMAXCONN for applications to be
 *                                      lower than the OS really supports (AIX...)
 *					Got rid of the MAX_CONNECTIONS stuff.
 *      Mike Williams   27-May-2010     Added prototype for dv_get_number by
 *                                      by defining NO_CSC
 */

/*
 *      Header Files:
 */
#include "flags.h"
#include "system.h"
#include <errno.h>                      /* ANSI-C compatible */
#include <stdio.h>                      /* ANSI-C compatible */
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>

#include "cl_pub.h"
#include "cl_ipc_pub.h"
#include "cl_qm.h"                      /* includes cl_qm_defs.h */
#include "ml_pub.h"

#define NOT_CSC
#ifdef NOT_CSC
#include "sblk_defs.h"
#include "dv_pub.h"
#else
#include "dv_api.h"
/* Macro to specify no additional message text for MLOGU, etc. */
#define MNOMSG  MMSG(0,"")     
#endif /* NOT_CSC */


/*
 *      Defines, Typedefs and Structure Definitions:
 */

/*
 *      Global and Static Variable Declarations:
 */
QM_QID  cl_write_q = 0;                 /* IPC output message queue         */

extern  int     max_retries;            /* maximum number of write retries  */

static  char   *self = "cl_ipc_create";


/*
 *      Procedure Type Declarations:
 */


STATUS 
cl_ipc_create (
    char *sock_name                     /* pointer to input socket name     */
)
{
    long     csi_tmo;
    long     csi_tries;
    int     i;
    char    lbuf[MAX_LOG_MSG_SIZE];


#ifdef DEBUG
    if TRACE(0)
        cl_trace("cl_ipc_create", 1,    /* routine name and parameter count */
                 (unsigned long)sock_name);
 
    /* check environment for well-known name changes */
    sock_name = cl_get_sockname(sock_name);
#endif /* DEBUG */


    /* check length of socket name */
    if (((i = strlen(sock_name)) < 1) || (i > SOCKET_NAME_SIZE)) {
        return (STATUS_INVALID_VALUE);
    }


    /* ensure input socket closed */
    if (sd_in >= 0) {

#ifdef IPC_SHARED
        /* detach from shared memory */
        if (small_preamble) {
            (void) shmdt((char *)small_preamble);
            small_preamble = 0;
        }
#endif /* IPC_SHARED */

        /* close socket */
        close(sd_in);
        sd_in = -1;
    }


#ifdef IPC_SHARED
    /* attach shared memory block */
    if (cl_sblk_attach() != TRUE) {
        MLOG((MMSG(121,"%s: Attaching to shared memory segment failed on \"%s\""), self,  strerror(errno)));
        return (STATUS_IPC_FAILURE);
    }
#endif /* IPC_SHARED */


    /* create input socket */
    if ((sd_in = cl_ipc_open(sock_name, my_sock_name)) < 0) {
        MLOG((MMSG(122,"%s: Creating socket %s failed on \"%s\""), self, 
                                sock_name, strerror(errno)));

#ifdef IPC_SHARED
        /* detach share memory */
        (void) shmdt((char *)small_preamble);
        small_preamble = 0;
#endif /* IPC_SHARED */

        return (STATUS_IPC_FAILURE);
    }

    /*
     *  At this point a socket is created and, if IPC_SHARED defined, shared
     *  memory is attached.  It should be okay to use the socket now.
     */

#ifndef IPC_SHARED
    /* set up connection limit */
    if (listen(sd_in, ((SOMAXCONN > 32) ? SOMAXCONN : 32)) < 0) {
        MLOGU((self, "listen", STATUS_IPC_FAILURE,
             MNOMSG));
        return (STATUS_IPC_FAILURE);
    }
#endif /* IPC_SHARED */


    /* initialize descriptor list */
    n_fds = 1;
    fd_list[0] = sd_in;


    /* destroy any previously created queue */
    if (cl_write_q) {
        (void)cl_qm_qdelete(cl_write_q);
        cl_write_q = 0;
    }


    /* set up write queue */
    if ( !cl_qm_init(1, "") )  {
        MLOGU((self, "cl_qm_init", STATUS_QUEUE_FAILURE,
             MNOMSG));
        return (STATUS_IPC_FAILURE);
    }
    sprintf(lbuf, "IPC write queue for PID %d", getpid());

    if ((cl_write_q = cl_qm_qcreate(0, lbuf)) == FALSE) {
        MLOGU((self, "cl_qm_qcreate", STATUS_QUEUE_FAILURE,
             MNOMSG));
        return (STATUS_IPC_FAILURE);
    }


    /* set up max_retries based on CSI network variable */
    if (dv_get_number(DV_TAG_CSI_RETRY_TIMEOUT, &csi_tmo) != STATUS_SUCCESS ) {
        csi_tmo = MAX_RETRY;
    }

    if (dv_get_number(DV_TAG_CSI_RETRY_TRIES, &csi_tries) != STATUS_SUCCESS ) {
        csi_tries = RETRY_TIMEOUT;
    }

    csi_tmo *= csi_tries;

    if (MAX_RETRY <= (csi_tmo / RETRY_TIMEOUT))
        max_retries = csi_tmo / RETRY_TIMEOUT + 5;
    else
        max_retries = MAX_RETRY;


    /* successfully created a socket */
    return (STATUS_SUCCESS);
}

