# $Revision: 1.12 $

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

DEPTH = ../../..

include $(DEPTH)/mk/common.mk

MAN_SRCS =  archiver.cmd.5 \
	defaults.conf.5 diskvols.conf.5 ftp.cmd.5 \
	fsalogd.cmd.5 hosts.fs.5 hosts.fs.local.5 \
	inquiry.conf.5 mcf.5 preview.cmd.5 \
	recycler.cmd.5 rft.cmd.5 \
	releaser.cmd.5 samdb.conf.5 samfs.cmd.5 sefdata.5 \
	sefsysevent.5 shrink.cmd.5

MAN_RELEASED_SRCS = archiver.cmd.5 \
	defaults.conf.5 diskvols.conf.5 ftp.cmd.5 \
	hosts.fs.5 hosts.fs.local.5 inquiry.conf.5 \
	mcf.5 preview.cmd.5  \
	recycler.cmd.5 rft.cmd.5 \
	releaser.cmd.5 samfs.cmd.5 sefdata.5 sefsysevent.5 \
	shrink.cmd.5

REM_RELEASED_SRCS = mcf.5

QFS_RELEASED_SRCS = mcf.5

include $(DEPTH)/mk/targets_man.mk

include $(DEPTH)/mk/depend.mk
