#!/bin/sh

# $Revision: 1.7 $

#    SAM-QFS_notice_begin
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at pkg/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at pkg/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#    SAM-QFS_notice_end

#
# Activate SAM-FS Preventive Maintenance.
#

TMP=/tmp/$$

echo "Copying /var/spool/cron/crontabs/sys to /var/tmp/crontabs.sys.sampm"
cp /var/spool/cron/crontabs/sys /var/tmp/crontabs.sys.sampm
echo "Activating sar (system activity reporter) crontab jobs ... crontab -e sys"
echo "#!/bin/sh" > $TMP
echo "/etc/opt/SUNWsamfs/sampm/edit -a sar -f \"\$1\"" >> $TMP
chmod a+rwx $TMP
EDITOR=$TMP VISUAL=$TMP crontab -e sys
rm -f $TMP

echo "Copying /var/spool/cron/crontabs/root to /var/tmp/crontabs.root.sampm"
cp /var/spool/cron/crontabs/root /var/tmp/crontabs.root.sampm
echo "Activating SAM-FS Preventive Maintenance crontab jobs ... crontab -e"
echo "#!/bin/sh" > $TMP
echo "/etc/opt/SUNWsamfs/sampm/edit -a pm -f \"\$1\"" >> $TMP
chmod a+rwx $TMP
EDITOR=$TMP VISUAL=$TMP crontab -e
rm -f $TMP

echo "Copying /etc/init.d/perf to /etc/init.d/perf.sampm"
cp /etc/init.d/perf /etc/init.d/perf.sampm
echo "Activating system activity data gathering ... /etc/init.d/perf"
/etc/opt/SUNWsamfs/sampm/edit -a perf

if [ ! -f /etc/opt/SUNWsamfs/defaults.conf ]; then
    touch /etc/opt/SUNWsamfs/defaults.conf
fi
echo "Copying /etc/opt/SUNWsamfs/defaults.conf to /etc/opt/SUNWsamfs/defaults.conf.sampm"
cp /etc/opt/SUNWsamfs/defaults.conf /etc/opt/SUNWsamfs/defaults.conf.sampm
echo "Activating SAM-FS logging ... /etc/opt/SUNWsamfs/defaults.conf"
/etc/opt/SUNWsamfs/sampm/edit -a defs > /dev/null
/opt/SUNWsamfs/sbin/samset devlog all all > /dev/null 2>&1
/opt/SUNWsamfs/sbin/samset debug all all > /dev/null 2>&1

echo "Activating performance collection ..."
/usr/lib/sa/sa1
/usr/lib/sa/sa2 -s 8:00 -e 18:01 -i 1200 -A

echo "Activating SEF read write counters collecting ..."
mkdir -p /var/opt/SUNWsamfs/sef > /dev/null 2>&1
touch /var/opt/SUNWsamfs/sef/sefdata

echo "Restarting SAM-FS sam-amld daemon ... "
/opt/SUNWsamfs/sbin/samd stop > /dev/null 2>&1
sleep 5
/opt/SUNWsamfs/sbin/samd start > /dev/null 2>&1

#
# Set file flag to know that sampm has been activated
#
touch /etc/opt/SUNWsamfs/sampm/.activate

exit 0
